# Generated by Django 3.1.2 on 2020-12-01 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('Code', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('HOD', models.CharField(default='', max_length=100)),
                ('Phone', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=100)),
                ('Course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.course')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(default='', max_length=100)),
                ('Middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('Last_name', models.CharField(default='', max_length=100)),
                ('Gender', models.CharField(default='', max_length=20)),
                ('Date_of_birth', models.CharField(default='', max_length=50)),
                ('Phone_number', models.CharField(default='', max_length=15)),
                ('Salary', models.IntegerField(default=0)),
                ('Grade', models.CharField(default='', max_length=10)),
                ('Designation', models.CharField(default='', max_length=20)),
                ('Age', models.IntegerField(default=0)),
                ('Course', models.ManyToManyField(to='accounts.Course')),
                ('Department', models.ManyToManyField(to='accounts.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Research_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('Area', models.CharField(default='', max_length=100)),
                ('Duration', models.CharField(default='', max_length=100)),
                ('Faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('University_id', models.CharField(default='TU', max_length=15, primary_key=True, serialize=False)),
                ('First_name', models.CharField(default='', max_length=100)),
                ('Middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('Last_name', models.CharField(default='', max_length=100)),
                ('Gender', models.CharField(default='', max_length=20)),
                ('Date_of_birth', models.CharField(default='', max_length=50)),
                ('Phone_number', models.CharField(default='', max_length=15)),
                ('Address', models.TextField(default='')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.course')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.department')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(default='', max_length=200)),
                ('Address', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=15)),
                ('Date_of_birth', models.CharField(default='', max_length=50)),
                ('Gender', models.CharField(default='', max_length=20)),
                ('Staff_id', models.CharField(default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.faculty')),
                ('Project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.research_project')),
            ],
        ),
    ]
